esphome:
  name: headless-fm-radio1
  friendly_name: headless-fm-radio1
  includes:
    - components/si4703/si4703.h
    - components/si4703/si4703_media_player.h
  packages:
    si4703: !include components/si4703
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:
api:
ota:
  - platform: esphome
sensor:
time:
  - platform: sntp
    timezone: "US/Mountain"
    servers:
      - 192.168.20.1
web_server:
  auth:
    username: admin
    password: !secret web_server_password 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Headless-Fm-Radio1"
    password: !secret web_server_password
captive_portal:
i2c:
  sda: GPIO16
  scl: GPIO17
  # scan: true # Optional: Uncomment to scan for I2C devices on boot

# Configure the base Si4703 component
si4703:
  id: fm_radio_chip
  # address: 0x10 # Optional: Uncomment if your device uses a non-default address

# Configure the media player using the Si4703 component
media_player:
  - platform: si4703
    name: "POE FM Radio"
    si4703_id: fm_radio_chip